import { v4 as uuidv4 } from 'uuid';
import {
  ScheduleBlock,
  Module,
  Habit,
  TimeString,
} from './schemas';

// ============= EXACT MODULES (per spec) =============
export const SEED_MODULES: Module[] = [
  {
    id: uuidv4(),
    code: 'ANALY2',
    name: 'Analysis 2',
    coefficient: 4,
    weakness: 2.5,
    priorityScore: (4 * 1.5) + 2.5, // 8.5
    isCritical: true,
    targetHoursPerWeek: 12,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'ALGO2',
    name: 'Algorithms 2',
    coefficient: 4,
    weakness: 1.5,
    priorityScore: (4 * 1.5) + 1.5, // 7.5
    isCritical: true,
    targetHoursPerWeek: 11,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'STRM',
    name: 'Streams & Complex Analysis',
    coefficient: 2,
    weakness: 3.0,
    priorityScore: (2 * 1.5) + 3.0, // 6.0
    isCritical: true,
    targetHoursPerWeek: 10,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'STAT',
    name: 'Statistics',
    coefficient: 2,
    weakness: 2.5,
    priorityScore: (2 * 1.5) + 2.5, // 5.5
    isCritical: true,
    targetHoursPerWeek: 9,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'ALG2',
    name: 'Algebra 2',
    coefficient: 2,
    weakness: 2.5,
    priorityScore: (2 * 1.5) + 2.5, // 5.5
    isCritical: false,
    targetHoursPerWeek: 5,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'OPM',
    name: 'Operations Management',
    coefficient: 1,
    weakness: 3.5,
    priorityScore: (1 * 1.5) + 3.5, // 5.0
    isCritical: false,
    targetHoursPerWeek: 4,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    code: 'ELEC',
    name: 'Electronics',
    coefficient: 2,
    weakness: 2.0,
    priorityScore: (2 * 1.5) + 2.0, // 5.0
    isCritical: false,
    targetHoursPerWeek: 6,
    createdAt: new Date(),
  },
];

// ============= EXACT SCHEDULE BLOCKS (from spec) =============
// Day of Week: 0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday

export const SEED_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  // ===== GLOBAL DAILY BLOCKS (all days) =====
  // 00:30-06:00 Sleep (all days)
  // 06:00 Choroq - Fajr Quran (all days)
  // 22:00-22:15 Typing (all days)
  // 22:15-23:15 Web Dev (all days)
  // Maghreb-Isha - Masjid Quran Review (all days, evening)

  // ========== MONDAY (dayOfWeek=0) ==========
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'University',
    details: 'ALG2 DW, ELEC DW, OPM, ALG2, ELEC',
    category: 'uni',
    weight: 2,
    timeKind: 'fixed',
    startTime: '08:00' as TimeString,
    endTime: '16:10' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Library STR M',
    details: 'Explain to friend (Feynman), priority 8',
    category: 'library',
    weight: 2,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '16:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Free Decompress',
    details: 'Food shower breathe',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'TD Prep Tuesday',
    details: 'STAT DW 35m weakest, ALGO2 DW 25m',
    category: 'tdprep',
    weight: 1,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'ELEC 30min',
    details: 'Exercises coef-2 maintenance',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '21:30' as TimeString,
    endTime: '22:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 0,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== TUESDAY (dayOfWeek=1) ==========
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'University',
    details: 'STAT DW, ALGO2 DW, STR M, ANALY2, STAT',
    category: 'uni',
    weight: 2,
    timeKind: 'fixed',
    startTime: '08:00' as TimeString,
    endTime: '16:10' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Library ANALY2',
    details: 'Hard problems w friend no rereading',
    category: 'library',
    weight: 2,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '16:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Free Decompress',
    details: 'Food shower breathe',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'TD Prep Wednesday',
    details: 'Algo TP 45m coef-4, OPM PW 15m',
    category: 'tdprep',
    weight: 1,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'STR M 30min',
    details: 'Reinforce priority 8 weakest module',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '21:30' as TimeString,
    endTime: '22:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 1,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== WEDNESDAY (dayOfWeek=2) - Gym Day 1 ==========
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'ANALY2 Deep Work',
    details: 'Hardest problems active recall only',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '09:00' as TimeString,
    endTime: '10:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Free Light Break',
    details: 'Prepare for TP review notes',
    category: 'free',
    weight: 1,
    timeKind: 'fixed',
    startTime: '10:30' as TimeString,
    endTime: '11:20' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'University',
    details: 'Algo TP, OPM PW',
    category: 'uni',
    weight: 2,
    timeKind: 'fixed',
    startTime: '11:20' as TimeString,
    endTime: '14:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Free Lunch',
    details: 'Eat reset 30min',
    category: 'free',
    weight: 1,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '15:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'ALGO2 TP Consolidation',
    details: 'Redo today TP fix every error',
    category: 'study',
    weight: 2,
    timeKind: 'fixed',
    startTime: '15:00' as TimeString,
    endTime: '16:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Gym Day 1',
    details: 'Full body Squat Push Row 3×8–12',
    category: 'gym',
    weight: 2,
    timeKind: 'fixed',
    startTime: '17:00' as TimeString,
    endTime: '17:50' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'TD Prep Thursday',
    details: 'STR M DW 35m weakest, ANALY2 DW 25m',
    category: 'tdprep',
    weight: 1,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'ALG2 30min',
    details: 'Exercises coef-2 maintenance',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '21:30' as TimeString,
    endTime: '22:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 2,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== THURSDAY (dayOfWeek=3) ==========
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'University',
    details: 'ANALY2 DW, STR M DW, ANALY2, ALGO2',
    category: 'uni',
    weight: 2,
    timeKind: 'fixed',
    startTime: '08:00' as TimeString,
    endTime: '14:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Library STAT',
    details: 'Problems w friend priority 8 weakest',
    category: 'library',
    weight: 2,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '16:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Free Decompress',
    details: 'Food shower breathe',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'ANALY2 45min',
    details: 'Reinforce today DW fix mistakes',
    category: 'study',
    weight: 2,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'ELEC 45min',
    details: 'Exercises priority 6 coef-2',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '21:15' as TimeString,
    endTime: '22:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 3,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== FRIDAY (dayOfWeek=4) - Max Deep Work ==========
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'ANALY2 Hard Set',
    details: 'Hardest problems of week no shortcuts',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '09:00' as TimeString,
    endTime: '10:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'STR M Hard Set',
    details: 'Priority 8 weakest needs this slot',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '10:30' as TimeString,
    endTime: '12:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Free Lunch Dhuhr',
    details: 'Eat pray rest recharge 1.5h max',
    category: 'free',
    weight: 1,
    timeKind: 'fixed',
    startTime: '12:00' as TimeString,
    endTime: '13:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'STAT 90min',
    details: 'Priority 8 weakest problem set',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '13:30' as TimeString,
    endTime: '15:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'ALG2 30min',
    details: 'Exercises medium priority',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '15:00' as TimeString,
    endTime: '15:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Free Family Walk',
    details: 'Earned rest after 5h study',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 60,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'ELEC 60min',
    details: 'Priority 6 coef-2 problem set',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 4,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== SATURDAY (dayOfWeek=5) - TIC + Gym Day 2 ==========
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'University TIC Distance',
    details: 'Online attend fully take notes',
    category: 'uni',
    weight: 1,
    timeKind: 'fixed',
    startTime: '09:40' as TimeString,
    endTime: '11:10' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Gym Day 2',
    details: 'Full body reps vs Wednesday track progress',
    category: 'gym',
    weight: 2,
    timeKind: 'fixed',
    startTime: '11:30' as TimeString,
    endTime: '12:20' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Recovery Shower Food',
    details: '40min then straight to study',
    category: 'free',
    weight: 1,
    timeKind: 'fixed',
    startTime: '12:20' as TimeString,
    endTime: '13:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'STR M 90min',
    details: 'Priority 8 weakest full problem set',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '13:00' as TimeString,
    endTime: '14:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'STAT 60min',
    details: 'Priority 8 problem solving',
    category: 'study',
    weight: 2,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '15:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Free Earned Rest',
    details: 'After gym 2.5h study deserved',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 60,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'ALG2 ALGO2 60min',
    details: 'ALG2 45m, ALGO2 review 15m',
    category: 'study',
    weight: 2,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 5,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ========== SUNDAY (dayOfWeek=6) - Reset + Gym Day 3 optional ==========
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Quran Memorization (Fajr)',
    details: 'Memorization leave 06:30',
    category: 'quran',
    weight: 2,
    timeKind: 'label',
    labelTime: 'Choroq',
    durationMinutes: 30,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Sleep',
    category: 'sleep',
    weight: 3,
    timeKind: 'fixed',
    startTime: '00:30' as TimeString,
    endTime: '06:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'ANALY2 Weekly Hard Set',
    details: 'Hardest problems push your limit',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '09:00' as TimeString,
    endTime: '10:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Gym Day 3',
    details: 'Full body optional if sore from Saturday',
    category: 'gym',
    weight: 2,
    timeKind: 'fixed',
    startTime: '10:45' as TimeString,
    endTime: '11:45' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Recovery Shower Food',
    details: '75min full recovery',
    category: 'free',
    weight: 1,
    timeKind: 'fixed',
    startTime: '11:45' as TimeString,
    endTime: '13:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'ALGO2 90min',
    details: 'Weekly hard set',
    category: 'study',
    weight: 3,
    timeKind: 'fixed',
    startTime: '13:00' as TimeString,
    endTime: '14:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'ELEC 60min',
    details: 'Priority 6 alternate with STR M each week',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '14:30' as TimeString,
    endTime: '15:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Free Family Recharged',
    details: 'Walk read no pressure Sunday reset',
    category: 'free',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Maghreb',
    durationMinutes: 60,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'TD Prep Monday',
    details: 'ALG2 DW 30m, ELEC DW 30m',
    category: 'tdprep',
    weight: 1,
    timeKind: 'fixed',
    startTime: '20:30' as TimeString,
    endTime: '21:30' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'STR M 30min',
    details: 'Reinforce never skip priority 8',
    category: 'study',
    weight: 1,
    timeKind: 'fixed',
    startTime: '21:30' as TimeString,
    endTime: '22:00' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Typing (keybr.com)',
    details: 'Log WPM every session',
    category: 'typing',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:00' as TimeString,
    endTime: '22:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Web Dev 1h',
    details: 'freeCodeCamp current phase',
    category: 'webdev',
    weight: 1,
    timeKind: 'fixed',
    startTime: '22:15' as TimeString,
    endTime: '23:15' as TimeString,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    dayOfWeek: 6,
    title: 'Masjid Quran Review',
    details: 'Evening',
    category: 'masjid',
    weight: 1,
    timeKind: 'label',
    labelTime: 'Isha',
    durationMinutes: 20,
    immutableBlockId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============= Core Habits (MVP only) =============
export const SEED_HABITS: Habit[] = [
  {
    id: uuidv4(),
    name: 'Quran Memorization',
    type: 'quran_memorization',
    targetFrequency: 'daily',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Masjid Quran Review',
    type: 'quran_review',
    targetFrequency: 'daily',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Typing Practice (keybr.com)',
    type: 'typing',
    targetFrequency: 'daily',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Web Development (1h)',
    type: 'webdev',
    targetFrequency: 'daily',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gym Training',
    type: 'gym',
    targetFrequency: 'weekly',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Sleep 6.5h+',
    type: 'sleep',
    targetFrequency: 'daily',
    currentStreak: 0,
    longestStreak: 0,
    lastCompletedDate: null,
    createdAt: new Date(),
  },
];
